name: Tests

on:
  push:
    branches: 
      - "**"
    tags-ignore:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-09-23
          components: rust-src, rustc-dev, llvm-tools-preview
          target: ${{ matrix.target }}
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v2
        with:
          name: flowistry-build
          path: |
            target/release/cargo-flowistry*
            target/release/flowistry-driver*

  test-rust:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - run: cargo test

  test-vscode:
    needs: build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-build
      - run: npm ci
        working-directory: ide
      - name: Run vscode tests
        run: xvfb-run -a npm test
        working-directory: ide

  install_release:
    name: Install extension with latest Flowistry release
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
        working-directory: ide
      - run: xvfb-run -a npm run test:install
        working-directory: ide
