name: Tests

on:
  push:
    branches: 
      - "**"
    tags-ignore:
      - "v*"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps: 
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-09-23
          components: rust-src, rustc-dev, llvm-tools-preview
          target: ${{ inputs.target }}
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - run: zip ${{ matrix.target }}.zip cargo-flowistry* flowistry-driver*
        working-directory: target/release
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - run: npm ci
        working-directory: ide
      - run: xvfb-run -a npm run test -- install --zip=../${{ matrix.target }}.zip
        working-directory: ide
