name: Tests

on:
  push:
    branches: 
      - "**"
    tags-ignore:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - run: cargo install --path .
      - uses: actions/upload-artifact@v2
        with:
          name: flowistry-build
          path: |
            ~/.cargo/bin/cargo-flowistry
            ~/.cargo/bin/flowistry-driver

  test:
    needs: build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Retrieve Flowistry build
        uses: actions/download-artifact@v2
        with:
          name: flowistry-build
      - run: cp -r ~/work/flowistry/flowistry/*flowistry*  ~/.cargo/bin/
      - run: chmod +x ~/.cargo/bin/*flowistry*
      - run: ls -l ~/.cargo/bin
      - run: cargo test
      - run: npm ci
        working-directory: ide
      - name: Run vscode tests
        run: xvfb-run -a npm test
        working-directory: ide

  install_release:
    name: Install extension with latest Flowistry release
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
        working-directory: ide
      - run: xvfb-run -a npm run test:install
        working-directory: ide
